version: "1.0"
services:
  project:
    build: .
    volumes:
      - .:/root/workspace
    env_file:
      - .env
    tty: true # retain container up
    command: /bin/bash
    shm_size: $DOCKER_SHM_SIZE
